---
title: "Sensitivity analysis"
output: html_document
date: "2023-05-08"
---

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)

ggtheme <- theme_minimal() +
  theme(legend.position = "none",
        axis.line = element_line(),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
theme_set(ggtheme)

unlist_scenarios <- function(x, what) {
  out <- purrr::map_df(x[[what]], ~as.data.frame(.x), .id = "scenario")
  out$scenario <- relevel(factor(out$scenario), "central")
  out
}
```

## Fitted trajectories


```{r, echo = FALSE, fig.width = 10}
traj <- unlist_scenarios(scenarios, "trajectories")
ggplot(traj, aes(date)) +
  geom_line(aes(y = mean, col = scenario)) +
  geom_ribbon(aes(ymin = lb, ymax = ub, fill = scenario), alpha = 0.3) +
  facet_grid(rows = vars(state), cols = vars(scenario), scales = "free_y") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_date(date_breaks = "2 month", date_labels = "%b-%y")
```


## Inferred transmissibility


```{r, echo = FALSE, fig.width = 10}
rt <- unlist_scenarios(scenarios, "rt")
ggplot(rt, aes(date)) +
  geom_line(aes(y = mean, col = scenario)) +
  geom_ribbon(aes(ymin = lb, ymax = ub, fill = scenario), alpha = 0.3) +
  facet_grid(rows = vars(state), cols = vars(scenario), scales = "free_y") +
  scale_y_continuous(expand = c(0, 0), breaks = seq(0, 10, 1)) +
  scale_x_date(date_breaks = "2 month", date_labels = "%b-%y")
```


## Inferred IFR


```{r, echo = FALSE, fig.width = 10}
ifr <- unlist_scenarios(scenarios, "severity")
ggplot(ifr, aes(date)) +
  geom_line(aes(y = mean, col = scenario)) +
  geom_ribbon(aes(ymin = lb, ymax = ub, fill = scenario), alpha = 0.3) +
  facet_grid(rows = vars(state), cols = vars(scenario), scales = "free_y") +
  scale_y_continuous(expand = c(0, 0), breaks = seq(0, 0.02, 0.005),
                     labels = scales::percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "2 month", date_labels = "%b-%y")
```

